import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from typing import Optional


def send_report_email(
    recipient: str,
    subject: str,
    body: str,
    attachment_path: Optional[str] = None,
    smtp_host: Optional[str] = None,
    smtp_port: Optional[int] = None,
    smtp_user: Optional[str] = None,
    smtp_pass: Optional[str] = None,
    use_tls: bool = True,
) -> dict:
    smtp_host = smtp_host or os.environ.get("SMTP_HOST", "")
    smtp_port = smtp_port or int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = smtp_user or os.environ.get("SMTP_USER", "") or os.environ.get("SMTP_USERNAME", "")
    smtp_pass = smtp_pass or os.environ.get("SMTP_PASS", "") or os.environ.get("SMTP_PASSWORD", "")
    smtp_from = os.environ.get("SMTP_FROM", "")

    if not all([smtp_host, smtp_user, smtp_pass]):
        return {
            "success": False,
            "message": (
                "Email not sent. SMTP credentials not configured. "
                "Please set SMTP_HOST, SMTP_PORT, SMTP_USER (or SMTP_USERNAME), "
                "SMTP_PASS (or SMTP_PASSWORD) as environment variables before using "
                "this feature. Example:\n"
                "  set SMTP_HOST=smtp.gmail.com\n"
                "  set SMTP_PORT=587\n"
                "  set SMTP_USER=your_email@gmail.com\n"
                "  set SMTP_PASS=your_app_password"
            ),
        }

    if not recipient or "@" not in recipient:
        return {"success": False, "message": "Invalid recipient email address."}

    msg = MIMEMultipart()
    msg["From"] = smtp_from or smtp_user
    msg["To"] = recipient
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    if attachment_path and os.path.exists(attachment_path):
        try:
            with open(attachment_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            filename = os.path.basename(attachment_path)
            part.add_header("Content-Disposition", f"attachment; filename={filename}")
            msg.attach(part)
        except Exception as e:
            return {"success": False, "message": f"Failed to attach file: {str(e)}"}

    try:
        server = smtplib.SMTP(smtp_host, smtp_port)
        if use_tls:
            server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, [recipient], msg.as_string())
        server.quit()
        return {"success": True, "message": f"Report sent successfully to {recipient}."}
    except smtplib.SMTPAuthenticationError:
        return {"success": False, "message": "SMTP authentication failed. Check your credentials."}
    except smtplib.SMTPConnectError:
        return {"success": False, "message": f"Could not connect to SMTP server at {smtp_host}:{smtp_port}."}
    except Exception as e:
        return {"success": False, "message": f"Email sending failed: {str(e)}"}


def build_email_body(
    project_name: str,
    npv: float,
    irr: float,
    mirr: float,
    roi: float,
    payback: float,
    risk_level: str,
    decision: str,
    main_reason: str,
    custom_message: str = "",
    currency: str = "USD",
) -> str:
    from data_validation import format_currency, format_pct

    if payback == float("inf"):
        payback_str = "Never recovers"
    else:
        payback_str = f"{payback:.1f} years"

    body = f"""
INVESTMENT DECISION REPORT
{'='*50}

Project: {project_name}
Currency: {currency}

EXECUTIVE SUMMARY
{'-'*50}
Final Decision: {decision}
NPV: {format_currency(npv, currency)}
IRR: {format_pct(irr)}
MIRR: {format_pct(mirr)}
ROI: {format_pct(roi)}
Payback Period: {payback_str}
Risk Level: {risk_level}

DECISION RATIONALE
{'-'*50}
{main_reason}

{custom_message}

{'='*50}
This report was generated by the Integrated Investment Decision Agent for Capital Projects.
For detailed analysis, please refer to the attached management report.
"""
    return body.strip()
